name: dotnet-framework

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup MSBuild
      - name: setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # Setup Nuget 
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2

      # Restore Nuget packages for project
      - name: Restore Packages
        run: nuget restore DynamicsCRMProvider.sln

      # Build project using a specific script
      - name: Build
        shell: cmd
        run: call .\build.cmd

      # Publish artifacts resulted from build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: DLL Build Result
          path: ./bin/*.dll
